name: React-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Use Node.js 13.10
      uses: actions/setup-node@v1
      with:
        node-version: '13.10'

    - name: Install yarn and run tests
      run: |
        yarn
        yarn test
      env:
        CI: true
